name: CI

on:
    push:
        branches: [main, develop]
        paths:
            - "src/**"
            - "tests/**"
            - "*.sln"
            - "*.csproj"
            - ".github/workflows/ci.yaml"
            - "GitVersion.yml"
    pull_request:
        branches: [main, develop]
        paths:
            - "src/**"
            - "tests/**"
            - "*.sln"
            - "*.csproj"
            - ".github/workflows/ci.yaml"
            - "GitVersion.yml"

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v3
              with:
                  versionSpec: "6.x"

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0
              with:
                  useConfigFile: true

            - name: Setup .NET  
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --no-build --verbosity normal --configuration Release
